import { StyleSheet } from 'react-native';

export const transactionsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F6F8',
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  topArea: {
    flexShrink: 0,
    paddingBottom: 6,
    zIndex: 2,
  },
  listArea: {
    flex: 1,
    minHeight: 0,
  },
  balanceCard: {
    backgroundColor: '#2da12b',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#2da12b',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  balanceLabel: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.75)',
    marginBottom: 6,
    fontWeight: '500',
  },
  balanceValue: {
    fontSize: 26,
    fontWeight: '700',
    color: '#FFF',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#444',
    marginBottom: 8,
    marginLeft: 2,
  },
  filterCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  filterAccordionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  filterAccordionButtonPressed: {
    opacity: 0.8,
  },
  filterHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filterBadge: {
    minWidth: 20,
    paddingHorizontal: 6,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#E8F5E9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2da12b',
  },
  filterBadgeText: {
    color: '#2da12b',
    fontSize: 11,
    fontWeight: '700',
  },
  filterChevron: {
    fontSize: 12,
    color: '#666',
    fontWeight: '700',
  },
  filterHeaderActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 10,
  },
  filterTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  clearFilters: {
    fontSize: 13,
    color: '#2da12b',
    fontWeight: '600',
  },
  filterLabel: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
    marginBottom: 8,
    marginTop: 4,
  },
  filterRow: {
    gap: 8,
    paddingBottom: 10,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#EEF0F2',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  filterChipSelected: {
    backgroundColor: '#E8F5E9',
    borderColor: '#2da12b',
  },
  filterChipText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  filterChipTextSelected: {
    color: '#2da12b',
    fontWeight: '700',
  },
  dateFilterRow: {
    flexDirection: 'row',
    gap: 10,
  },
  dateFilterButton: {
    flex: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: '#E1E5E8',
    backgroundColor: '#FAFBFC',
  },
  dateFilterLabel: {
    fontSize: 11,
    color: '#7A7A7A',
    marginBottom: 2,
    fontWeight: '600',
  },
  dateFilterValue: {
    fontSize: 13,
    color: '#1A1A1A',
    fontWeight: '500',
  },
  list: {
    paddingTop: 4,
    paddingBottom: 100,
  },
  emptyContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    fontSize: 15,
    color: '#AAAAAA',
    textAlign: 'center',
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  itemPressed: {
    opacity: 0.75,
  },
  iconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  iconText: {
    fontSize: 18,
    fontWeight: '700',
  },
  itemInfo: {
    flex: 1,
  },
  itemType: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  itemSub: {
    fontSize: 12,
    color: '#999',
    marginTop: 2,
    textTransform: 'capitalize',
  },
  itemRight: {
    alignItems: 'flex-end',
  },
  itemValue: {
    fontSize: 15,
    fontWeight: '700',
  },
  itemDate: {
    fontSize: 11,
    color: '#BBB',
    marginTop: 3,
  },
  deleteButton: {
    marginTop: 8,
    backgroundColor: '#FDECEC',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  deleteButtonPressed: {
    opacity: 0.85,
  },
  deleteButtonText: {
    color: '#C62828',
    fontSize: 11,
    fontWeight: '700',
  },
  endList: {
    textAlign: 'center',
    color: '#AAAAAA',
    fontSize: 12,
    marginBottom: 22,
  },
  fab: {
    position: 'absolute',
    bottom: 28,
    right: 20,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#2da12b',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2da12b',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  fabPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.94 }],
  },
  fabIcon: {
    fontSize: 28,
    color: '#FFF',
    fontWeight: '300',
    lineHeight: 32,
  },
});
